import { Buffer } from "node:buffer";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { McAssetError } from "../../src/core/errors.ts";
import { decodeImage, detectImageFormat } from "../../src/io/decode.ts";

/**
 * Fixture provenance (self-made, no Mojang assets):
 * - px-8x8.png: generated by pngjs from an inline 8x8 RGBA pattern;
 *   (0,0) = 200,10,90,0 hidden-RGB probe, (7,7) = 30,60,120,128.
 * - px-8x8.jpg: the same pattern composited onto black (JPEG has no
 *   alpha) and encoded with jpeg-js 0.4.4 quality 90.
 * - px-lossless.webp: cwebp 1.6.0 `-lossless -exact` from px-8x8.png.
 * - px-lossy-q80.webp: cwebp 1.6.0 `-q 80` from px-8x8.png.
 */

const FIXTURES = join(
	dirname(fileURLToPath(import.meta.url)),
	"..",
	"cli",
	"fixtures",
);

function fixture(name: string): Uint8Array {
	return new Uint8Array(readFileSync(join(FIXTURES, name)));
}

/** Runner-agnostic assertion surface for async decode cases. */
export interface DecodeCheck {
	equal(actual: unknown, expected: unknown, message?: string): void;
	deepEqual(actual: unknown, expected: unknown, message?: string): void;
	ok(value: unknown, message?: string): void;
	fail(message: string): never;
	throwsCodeAsync(
		fn: () => Promise<unknown>,
		code: string,
		message?: string,
	): Promise<void>;
}

export interface DecodeCase {
	name: string;
	run(check: DecodeCheck): Promise<void>;
}

function pngProbe(
	check: DecodeCheck,
	pixels: Uint8Array,
	width: number,
	height: number,
): void {
	check.equal(width, 8, "width");
	check.equal(height, 8, "height");
	const at = (x: number, y: number): number[] => {
		const o = (y * 8 + x) * 4;
		return [pixels[o], pixels[o + 1], pixels[o + 2], pixels[o + 3]];
	};
	check.deepEqual(at(0, 0), [200, 10, 90, 0], "hidden-RGB probe survives");
}

export const DECODE_CASES: DecodeCase[] = [
	{
		name: "detects png, jpeg, and webp by magic bytes",
		run: async (check) => {
			check.equal(detectImageFormat(fixture("px-8x8.png")), "png", "png");
			check.equal(detectImageFormat(fixture("px-8x8.jpg")), "jpeg", "jpeg");
			check.equal(
				detectImageFormat(fixture("px-lossless.webp")),
				"webp",
				"webp",
			);
			check.equal(
				detectImageFormat(new Uint8Array(Buffer.from("hello world"))),
				"unknown",
				"unknown",
			);
			check.equal(detectImageFormat(new Uint8Array(0)), "unknown", "empty");
		},
	},
	{
		name: "png decodes through the shared entry with probe intact",
		run: async (check) => {
			const decoded = await decodeImage(fixture("px-8x8.png"));
			check.equal(decoded.format, "png", "format");
			pngProbe(check, decoded.pixels, decoded.width, decoded.height);
		},
	},
	{
		name: "jpeg decodes to opaque 8x8 without premultiply artifacts",
		run: async (check) => {
			const decoded = await decodeImage(fixture("px-8x8.jpg"));
			check.equal(decoded.format, "jpeg", "format");
			check.equal(decoded.width, 8, "width");
			check.equal(decoded.height, 8, "height");
			for (let i = 3; i < decoded.pixels.length; i += 4) {
				check.equal(decoded.pixels[i], 255, `opaque alpha at byte ${i}`);
			}
		},
	},
	{
		name: "lossless webp keeps the hidden-RGB probe (no premultiply)",
		run: async (check) => {
			const decoded = await decodeImage(fixture("px-lossless.webp"));
			check.equal(decoded.format, "webp", "format");
			pngProbe(check, decoded.pixels, decoded.width, decoded.height);
		},
	},
	{
		name: "lossy webp decodes to the expected dimensions",
		run: async (check) => {
			const decoded = await decodeImage(fixture("px-lossy-q80.webp"));
			check.equal(decoded.format, "webp", "format");
			check.equal(decoded.width, 8, "width");
			check.equal(decoded.height, 8, "height");
		},
	},
	{
		name: "input bytes are never mutated by decode",
		run: async (check) => {
			const input = fixture("px-lossless.webp");
			const before = Uint8Array.from(input);
			await decodeImage(input);
			check.deepEqual(Array.from(input), Array.from(before), "bytes intact");
		},
	},
	{
		name: "corrupt inputs map to UNSUPPORTED_IMAGE_FORMAT",
		run: async (check) => {
			const png = fixture("px-8x8.png").subarray(0, 20);
			await check.throwsCodeAsync(
				() => decodeImage(png),
				"UNSUPPORTED_IMAGE_FORMAT",
				"truncated png",
			);
			const jpg = fixture("px-8x8.jpg").subarray(0, 20);
			await check.throwsCodeAsync(
				() => decodeImage(jpg),
				"UNSUPPORTED_IMAGE_FORMAT",
				"truncated jpeg",
			);
			const webp = fixture("px-lossless.webp").subarray(0, 12);
			await check.throwsCodeAsync(
				() => decodeImage(webp),
				"UNSUPPORTED_IMAGE_FORMAT",
				"truncated webp",
			);
			await check.throwsCodeAsync(
				() => decodeImage(new Uint8Array(Buffer.from("not an image"))),
				"UNSUPPORTED_IMAGE_FORMAT",
				"unknown bytes",
			);
		},
	},
	{
		name: "unsupported container is UNSUPPORTED_IMAGE_FORMAT, not a crash",
		run: async (check) => {
			const gif = new Uint8Array(
				Buffer.from(
					"GIF89a\u0001\u0000\u0001\u0000\u0080\u0000\u0000",
					"binary",
				),
			);
			try {
				await decodeImage(gif);
			} catch (error) {
				check.ok(
					error instanceof McAssetError &&
						error.code === "UNSUPPORTED_IMAGE_FORMAT",
					"gif rejected with format code",
				);
				return;
			}
			check.fail("gif input must be rejected");
		},
	},
];
