import { Buffer } from "node:buffer";
import {
	addLayer,
	createCanvas,
	getPixel,
	setPixel,
} from "../../src/core/canvas.ts";
import type { PixelCanvas } from "../../src/core/types.ts";
import { decodePng, encodePng, flattenCanvas } from "../../src/io/png.ts";

/** Runner-agnostic assertion surface: bun:test and node:test entries adapt to this. */
export interface CaseCheck {
	equal(actual: unknown, expected: unknown, message?: string): void;
	deepEqual(actual: unknown, expected: unknown, message?: string): void;
	ok(value: unknown, message?: string): void;
	fail(message: string): never;
	throwsCode(fn: () => unknown, code: string, message?: string): void;
}

export interface PngCase {
	name: string;
	run(check: CaseCheck): void;
}

function fromBase64(literal: string): Uint8Array {
	return new Uint8Array(Buffer.from(literal, "base64"));
}

function bytesEqual(
	check: CaseCheck,
	actual: Uint8Array,
	expected: readonly number[],
	message: string,
): void {
	check.equal(actual.length, expected.length, `${message} (length)`);
	for (let i = 0; i < expected.length; i += 1) {
		check.equal(actual[i], expected[i], `${message} (byte ${i})`);
	}
}

/** Fixed test vectors. Each is a literal: never generated by the code under test. */
export const PNG_VECTORS = {
	/** §75 fixture: 1x1 RGBA8 #FF000000. Hand-assembled IHDR+IDAT+IEND. */
	V75_1X1_TRANSPARENT_RED:
		"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4AWP4z8DAAAAEAQEAtXZJLAAAAABJRU5ErkJggg==",
	/** Codec proof: 2x2 RGBA8, every pixel A=0 with distinct hidden RGB. Row 1 uses Sub filter. */
	V_PATTERN_2X2:
		"iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAGUlEQVR4AWP4zwAE/xkYGBkY/jMIKpkwAAAkCgNmUP1fDAAAAABJRU5ErkJggg==",
	/** §101.2 grayscale: 2x1 gray 0 and 200. */
	V_GRAY_2X1:
		"iVBORw0KGgoAAAANSUhEUgAAAAIAAAABCAAAAADRSSBWAAAAC0lEQVR4AWNgOAEAAMsAyV2dwDUAAAAASUVORK5CYII=",
	/** §101.2 palette + tRNS: 2x1 red opaque, green with alpha 0. */
	V_PALETTE_TRNS_2X1:
		"iVBORw0KGgoAAAANSUhEUgAAAAIAAAABCAMAAADD/I+4AAAABlBMVEX/AAAA/wDSh+9xAAAAAnRSTlP/AOW3MEoAAAAMSURBVHgBY2BgZAAAAAYAAopWJcEAAAAASUVORK5CYII=",
	/** §101.2 16-bit RGBA: px0 0x12FF/0x3400/0x00FF/0xFFFF, px1 0xFF00/0x0080/0x8080/0x8000. */
	V_16BIT_2X1:
		"iVBORw0KGgoAAAANSUhEUgAAAAIAAAABEAYAAACksqPJAAAAFklEQVR4AWMQ+m/CwPAfCBgYGoCAAQA/1AdC1Y6WUwAAAABJRU5ErkJggg==",
	/** §101.2 interlace: Adam7 1x1 RGBA (9,8,7,0). */
	V_INTERLACED_1X1:
		"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAFoEvQfAAAADUlEQVR4AWPg5GBnAAAATwAZIfwwPgAAAABJRU5ErkJggg==",
	/** §101.2 gAMA 45455 with 1x1 #FF000000: pixels must pass through untouched. */
	V_GAMA_1X1:
		"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAABGdBTUEAALGPC/xhBQAAAA1JREFUeAFj+M/AwAAABAEBALV2SSwAAAAASUVORK5CYII=",
	/** §101.2 iCCP with 1x1 (1,2,3,4): pixels must pass through untouched. */
	V_ICCP_1X1:
		"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAJGlDQ1B0ZXN0AAB4nEtLzE7VzUxO1i0oyk/LzEnVTaosSS0GAF5SCGZPeJ/LAAAADUlEQVR4AWNgZGJmAQAAGQALFSrFVgAAAABJRU5ErkJggg==",
	/** §102: same bytes as the §75 vector but IHDR width patched to 5000. */
	V_OVERSIZE_W5000:
		"iVBORw0KGgoAAAANSUhEUgAAE4gAAAABCAYAAAAyEUSIAAAADUlEQVR4AWP4z8DAAAAEAQEAtXZJLAAAAABJRU5ErkJggg==",
	/** Not a PNG at all. base64 of "this is not a PNG file". */
	V_NOT_PNG: "dGhpcyBpcyBub3QgYSBQTkcgZmlsZQ==",
} as const;

function decodePixels(canvas: PixelCanvas): Array<{
	r: number;
	g: number;
	b: number;
	a: number;
}> {
	const layer = canvas.layers[0];
	if (layer === undefined) {
		throw new Error("decoded canvas must carry exactly one layer");
	}
	const out: Array<{ r: number; g: number; b: number; a: number }> = [];
	for (let y = 0; y < canvas.height; y += 1) {
		for (let x = 0; x < canvas.width; x += 1) {
			out.push(getPixel(canvas, layer.id, x, y));
		}
	}
	return out;
}

function seedCanvas(
	pixels: ReadonlyArray<{
		r: number;
		g: number;
		b: number;
		a: number;
	}>,
): PixelCanvas {
	const canvas = createCanvas(2, 2);
	const layer = addLayer(canvas, { id: "base" });
	let i = 0;
	for (let y = 0; y < 2; y += 1) {
		for (let x = 0; x < 2; x += 1) {
			const color = pixels[i];
			if (color === undefined) {
				throw new Error("seed pixel missing");
			}
			setPixel(canvas, layer.id, x, y, color);
			i += 1;
		}
	}
	return canvas;
}

export const PNG_CASES: PngCase[] = [
	{
		name: "codec proof: A=0 pattern survives decode, encode, decode",
		run: (check) => {
			const input = fromBase64(PNG_VECTORS.V_PATTERN_2X2);
			const before = Uint8Array.from(input);
			const first = decodePng(input);
			check.equal(first.canvas.width, 2, "width");
			check.equal(first.canvas.height, 2, "height");
			check.deepEqual(
				decodePixels(first.canvas),
				[
					{ r: 255, g: 0, b: 0, a: 0 },
					{ r: 0, g: 255, b: 0, a: 0 },
					{ r: 0, g: 0, b: 255, a: 0 },
					{ r: 17, g: 34, b: 51, a: 0 },
				],
				"hidden RGB kept verbatim",
			);
			// No premultiply anywhere on the encode path either.
			const encoded = encodePng(first.canvas);
			const second = decodePng(encoded);
			check.deepEqual(
				decodePixels(second.canvas),
				decodePixels(first.canvas),
				"round-trip pixels identical",
			);
			bytesEqual(check, input, Array.from(before), "input bytes untouched");
		},
	},
	{
		name: "section 75: #FF000000 round-trips through PNG",
		run: (check) => {
			const input = fromBase64(PNG_VECTORS.V75_1X1_TRANSPARENT_RED);
			const before = Uint8Array.from(input);
			const decoded = decodePng(input);
			check.deepEqual(
				decodePixels(decoded.canvas),
				[{ r: 255, g: 0, b: 0, a: 0 }],
				"#FF000000 kept, not #00000000",
			);
			const encoded = encodePng(decoded.canvas);
			check.deepEqual(
				decodePixels(decodePng(encoded).canvas),
				[{ r: 255, g: 0, b: 0, a: 0 }],
				"second pass keeps #FF000000",
			);
			bytesEqual(check, input, Array.from(before), "input bytes untouched");
		},
	},
	{
		name: "16-bit input keeps the high 8 bits",
		run: (check) => {
			const decoded = decodePng(fromBase64(PNG_VECTORS.V_16BIT_2X1));
			check.deepEqual(
				decodePixels(decoded.canvas),
				[
					{ r: 18, g: 52, b: 0, a: 255 },
					{ r: 255, g: 0, b: 128, a: 128 },
				],
				"high 8 bits, not rescaled rounding",
			);
		},
	},
	{
		name: "palette plus tRNS expands to RGBA8",
		run: (check) => {
			const decoded = decodePng(fromBase64(PNG_VECTORS.V_PALETTE_TRNS_2X1));
			check.deepEqual(
				decodePixels(decoded.canvas),
				[
					{ r: 255, g: 0, b: 0, a: 255 },
					{ r: 0, g: 255, b: 0, a: 0 },
				],
				"PLTE colors with tRNS alpha",
			);
		},
	},
	{
		name: "grayscale input expands to RGBA8",
		run: (check) => {
			const decoded = decodePng(fromBase64(PNG_VECTORS.V_GRAY_2X1));
			check.deepEqual(
				decodePixels(decoded.canvas),
				[
					{ r: 0, g: 0, b: 0, a: 255 },
					{ r: 200, g: 200, b: 200, a: 255 },
				],
				"gray replicated, alpha opaque",
			);
		},
	},
	{
		name: "interlaced input decodes as plain RGBA8",
		run: (check) => {
			const decoded = decodePng(fromBase64(PNG_VECTORS.V_INTERLACED_1X1));
			check.deepEqual(
				decodePixels(decoded.canvas),
				[{ r: 9, g: 8, b: 7, a: 0 }],
				"Adam7 accepted",
			);
			// Re-encode normalizes to non-interlaced output without losing pixels.
			check.deepEqual(
				decodePixels(decodePng(encodePng(decoded.canvas)).canvas),
				[{ r: 9, g: 8, b: 7, a: 0 }],
				"re-encoded pixels identical",
			);
		},
	},
	{
		name: "gAMA is ignored for pixels and reported as a warning",
		run: (check) => {
			const decoded = decodePng(fromBase64(PNG_VECTORS.V_GAMA_1X1));
			check.deepEqual(
				decodePixels(decoded.canvas),
				[{ r: 255, g: 0, b: 0, a: 0 }],
				"gamma does not touch pixels",
			);
			check.ok(
				decoded.warnings.some((warning) => warning.code === "GAMMA_IGNORED"),
				"GAMMA_IGNORED warning present",
			);
		},
	},
	{
		name: "iCCP is ignored for pixels and reported as a warning",
		run: (check) => {
			const decoded = decodePng(fromBase64(PNG_VECTORS.V_ICCP_1X1));
			check.deepEqual(
				decodePixels(decoded.canvas),
				[{ r: 1, g: 2, b: 3, a: 4 }],
				"color profile does not touch pixels",
			);
			check.ok(
				decoded.warnings.some((warning) => warning.code === "ICCP_IGNORED"),
				"ICCP_IGNORED warning present",
			);
		},
	},
	{
		name: "plain vectors carry no warnings",
		run: (check) => {
			const decoded = decodePng(fromBase64(PNG_VECTORS.V_PATTERN_2X2));
			check.deepEqual(decoded.warnings, [], "no warnings without gAMA/iCCP");
		},
	},
	{
		name: "same canvas encodes byte-identical twice",
		run: (check) => {
			const canvas = seedCanvas([
				{ r: 255, g: 0, b: 0, a: 0 },
				{ r: 0, g: 255, b: 0, a: 255 },
				{ r: 0, g: 0, b: 255, a: 128 },
				{ r: 17, g: 34, b: 51, a: 0 },
			]);
			const first = encodePng(canvas);
			const second = encodePng(canvas);
			bytesEqual(check, first, Array.from(second), "byte-stable output");
		},
	},
	{
		name: "flatten: single opaque layer is an exact copy",
		run: (check) => {
			const canvas = createCanvas(2, 1);
			const layer = addLayer(canvas, { id: "base" });
			setPixel(canvas, layer.id, 0, 0, { r: 10, g: 20, b: 30, a: 255 });
			setPixel(canvas, layer.id, 1, 0, { r: 40, g: 50, b: 60, a: 255 });
			bytesEqual(
				check,
				flattenCanvas(canvas),
				[10, 20, 30, 255, 40, 50, 60, 255],
				"exact copy",
			);
		},
	},
	{
		name: "flatten: hidden layer is skipped",
		run: (check) => {
			const canvas = createCanvas(1, 1);
			const bottom = addLayer(canvas, { id: "bottom" });
			setPixel(canvas, bottom.id, 0, 0, { r: 255, g: 0, b: 0, a: 255 });
			const top = addLayer(canvas, { id: "top", visible: false });
			setPixel(canvas, top.id, 0, 0, { r: 0, g: 255, b: 0, a: 255 });
			bytesEqual(check, flattenCanvas(canvas), [255, 0, 0, 255], "top ignored");
		},
	},
	{
		name: "flatten: opacity 0 contributes nothing",
		run: (check) => {
			const canvas = createCanvas(1, 1);
			const bottom = addLayer(canvas, { id: "bottom" });
			setPixel(canvas, bottom.id, 0, 0, { r: 0, g: 0, b: 255, a: 255 });
			const top = addLayer(canvas, { id: "top", opacity: 0 });
			setPixel(canvas, top.id, 0, 0, { r: 255, g: 0, b: 0, a: 255 });
			bytesEqual(
				check,
				flattenCanvas(canvas),
				[0, 0, 255, 255],
				"bottom shows through",
			);
		},
	},
	{
		name: "flatten: opacity 0.5 composites deterministically",
		run: (check) => {
			// Half red over transparent: alpha halves, color stays.
			const solo = createCanvas(1, 1);
			const film = addLayer(solo, { id: "film", opacity: 0.5 });
			setPixel(solo, film.id, 0, 0, {
				r: 255,
				g: 0,
				b: 0,
				a: 255,
			});
			bytesEqual(check, flattenCanvas(solo), [255, 0, 0, 128], "half alpha");
			// Half red over opaque blue: src-over in straight-alpha space.
			const over = createCanvas(1, 1);
			const base = addLayer(over, { id: "base" });
			setPixel(over, base.id, 0, 0, { r: 0, g: 0, b: 255, a: 255 });
			const glaze = addLayer(over, { id: "glaze", opacity: 0.5 });
			setPixel(over, glaze.id, 0, 0, { r: 255, g: 0, b: 0, a: 255 });
			bytesEqual(
				check,
				flattenCanvas(over),
				[128, 0, 127, 255],
				"src-over at half opacity",
			);
		},
	},
	{
		name: "flatten: fully transparent result keeps the top hidden RGB",
		run: (check) => {
			const canvas = createCanvas(1, 1);
			const layer = addLayer(canvas, { id: "base" });
			setPixel(canvas, layer.id, 0, 0, { r: 17, g: 34, b: 51, a: 0 });
			bytesEqual(
				check,
				flattenCanvas(canvas),
				[17, 34, 51, 0],
				"hidden RGB preserved",
			);
		},
	},
	{
		name: "width above 4096 is rejected before any buffer work",
		run: (check) => {
			const input = fromBase64(PNG_VECTORS.V_OVERSIZE_W5000);
			check.equal(input.length, 70, "vector is the 1x1 with patched width");
			check.throwsCode(
				() => decodePng(input),
				"INVALID_DIMENSION",
				"oversize width",
			);
		},
	},
	{
		name: "non-PNG bytes are reported as unsupported format",
		run: (check) => {
			check.throwsCode(
				() => decodePng(fromBase64(PNG_VECTORS.V_NOT_PNG)),
				"UNSUPPORTED_IMAGE_FORMAT",
				"bad signature",
			);
			const truncated = fromBase64(
				PNG_VECTORS.V75_1X1_TRANSPARENT_RED,
			).subarray(0, 20);
			check.throwsCode(
				() => decodePng(truncated),
				"UNSUPPORTED_IMAGE_FORMAT",
				"truncated file",
			);
		},
	},
];
